$engine: 3
$onesync: on
name: NPKTeam ESX + Overextended
author: NPKTeam
description: Custom ESX Legacy recipe with Overextended resources (ox_lib, ox_inventory, ox_target, ox_fuel, ox_doorlock, oxmysql), containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat
  
  # Download and prepare server.cfg
  - action: download_github
    src: https://github.com/Nirwos/npkteam-esx-overextended
    ref: main
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/overextended.cfg
    dest: ./overextended.cfg

  - action: move_path
    src: ./tmp/recipe/NPKTeam.png
    dest: ./NPKTeam.png

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons/
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]

  - action: move_path
    src: ./tmp/addons/[esx_addons]
    dest: ./resources/[esx_addons]

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  # Download Overextended resources
  - action: download_github
    src: https://github.com/communityox/ox_lib
    ref: main
    dest: ./resources/[ox]/ox_lib

  - action: download_github
    src: https://github.com/communityox/oxmysql
    ref: main
    dest: ./resources/[ox]/oxmysql

  - action: download_github
    src: https://github.com/communityox/ox_inventory
    ref: main
    dest: ./resources/[ox]/ox_inventory

  - action: download_github
    src: https://github.com/communityox/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  - action: download_github
    src: https://github.com/communityox/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  - action: download_github
    src: https://github.com/communityox/ox_doorlock
    ref: main
    dest: ./resources/[ox]/ox_doorlock

  ## Cleanup
  - action: remove_path
    path: ./tmp
