$engine: 3
$onesync: on
name: NPKTeam ESX + Overextended
author: NPKTeam
description: Custom ESX Legacy recipe with Overextended resources (ox_lib, ox_inventory, ox_target, ox_fuel, ox_doorlock, oxmysql), containing Jobs, Housing, Vehicles & more!

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat
  
  # Download and prepare server.cfg
  - action: download_github
    src: https://github.com/Nirwos/npkteam-esx-overextended
    ref: main
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/overextended.cfg
    dest: ./overextended.cfg

  - action: move_path
    src: ./tmp/recipe/NPKTeam.png
    dest: ./NPKTeam.png

  # Download basic resources and ESX dependencies

  - action: connect_database

  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql

  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons/
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]

  - action: move_path
    src: ./tmp/addons/[esx_addons]
    dest: ./resources/[esx_addons]

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice

  # Download Overextended resources (latest releases)
  - action: download_file
    path: ./tmp/files/ox_lib.zip
    url: https://github.com/communityox/ox_lib/releases/latest/download/ox_lib.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_lib.zip

  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/communityox/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/oxmysql.zip

  - action: download_file
    path: ./tmp/files/ox_inventory.zip
    url: https://github.com/communityox/ox_inventory/releases/latest/download/ox_inventory.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_inventory.zip

  - action: download_file
    path: ./tmp/files/ox_target.zip
    url: https://github.com/communityox/ox_target/releases/latest/download/ox_target.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_target.zip

  - action: download_file
    path: ./tmp/files/ox_fuel.zip
    url: https://github.com/communityox/ox_fuel/releases/latest/download/ox_fuel.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_fuel.zip

  - action: download_file
    path: ./tmp/files/ox_doorlock.zip
    url: https://github.com/communityox/ox_doorlock/releases/latest/download/ox_doorlock.zip
  - action: unzip
    dest: ./resources/[ox]
    src: ./tmp/files/ox_doorlock.zip

  ## Cleanup
  - action: remove_path
    path: ./tmp
